from time import sleep
print("selamat datang!, kamu yang ulang tahun \U0001F973:)")
sleep(4)
waktu = input("jam 12  5/11(saat ini) : ")
sleep(0.25)
nama = input("Queen Cina : ")
sleep(0.75)
umur = input("21 Tahun : ")
sleep (2)
print ("selamat datang", Queen)
sleep (1)
print(waktu)
sleep(4)
print("selamat ulang tahun ke-", 21 , Queen)
sleep(3)
print("         \U0001F525   \U0001F525")
print("          |    |")
sleep(1)
print("          |    |")
sleep(1)
print("       ------------")
sleep(1)
print("       |          |")
sleep(1)
print("       |          |")
sleep(1)
print("       ------------")
sleep(2)
print("  ----------------------")
sleep(1)
print("  |                    |")
sleep(1)
print("  |                    |")
sleep(1)
print("  ----------------------")
sleep(3)
print("semoga panjang umur,")
sleep(2)
print("sehat selalu, dan bisa membanggakan orang tua \U0001F44D \U0001F44D")
sleep(3)
print("aku akan selalu mendoa'kan yang terbaik untuk kamu")